import SavedCard from "./savedCard"
import { useEffect, useState, MouseEvent } from "react"
import { object } from "zod"

interface AppProps {
  location?: string
  zipcode?: number
}

interface Card {
  location?: string
  zipcode?: number
  key?: number
}

export const DashBoard = (props: AppProps) => {
  // Edit TS here: create Zod schema?
  const [cards, setCards] = useState<Card[]>([])
  const [zipcode, setZipcode] = useState<number>()
  const [location, setLocation] = useState<string>()

  useEffect(() => {
    setZipcode(props.zipcode)
    setLocation(props.location)
  }, [props, zipcode, location])

  // Edit TS - mouseevent does not work
  function removeCard(e: any) {
    // can refactor here if needed
    const badCard = cards.findIndex((card: Card) => card.zipcode === Number(e.target.name))

    setCards(cards.filter((card: Card, index: number) => index != badCard))
  }

  function createCard() {
    // prevents duplicate cards
    for (let card of cards) {
      if (zipcode === card.zipcode) {
        console.log("card already exists")
        return
      }
    }

    setCards([
      ...cards,
      {
        location: location,
        zipcode: zipcode,
        key: zipcode,
      },
    ])
  }

  function handleEvent() {}

  // useEffect(() => {
  //   console.log(cards)
  // }, [cards])

  // need to format scrollbar
  return (
    <>
      <div className="bg-slate-500 w-3/4 h-1/8 flex items-center justify-center border-4 border-slate-400 rounded shadow-sm shadow-black m-1 box-border">
        <button
          className="border-2 border-slate-700 rounded-xl shadow-md shadow-slate-700 grid place-items-center p-2 bg-slate-400 place-self-start m-2"
          onClick={createCard}
        >
          Add Location To Favorites
        </button>
        <div>
          <ul className="flex flex-row overflow-x-scroll">
            {cards
              ? cards.map((card: any) => {
                  return (
                    <li
                      id="location-card"
                      className="border-2 border-slate-700 rounded-xl shadow-md shadow-slate-700 grid place-items-center p-2 bg-slate-400 m-2 w-44"
                      key={card.key}
                    >
                      <div className="text-center">Location: {card.location}</div>
                      <div className="text-center">Zipcode: {card.zipcode}</div>
                      <button onClick={removeCard} name={card.zipcode} className="text-center">
                        Remove Card
                      </button>
                    </li>
                  )
                })
              : "Loading"}
          </ul>
        </div>
      </div>
      <button>New Event</button>
      <button onClick={handleEvent}>Handle Event</button>
    </>
  )
}

// Structure
// autogenerated cards
// displays name & zipcode
// Save to Favorites Button

// Functionality
// CRUD on user model - buttons to reflect this
// on click - sets SearchBar location call to saved zipcode

export default DashBoard
