import SearchBar from "./searchBar"
import SavedCard from "./savedCard"
import { useEffect, useState } from "react"

interface AppProps {
  location?: string
  zipcode?: number
}

export const DashBoard = (props: AppProps) => {
  // Edit TS here: create Zod schema?
  const [cards, setCards] = useState<Array<any | undefined>>()
  const [zipcode, setZipcode] = useState<number>()
  const [location, setLocation] = useState<string>()

  function removeCard(zipcode: any) {
    // const badCard = cards?.find(card => card.props.location === `${zipcode}`)
    // console.log(badCard);
    console.log("hello")
  }

  function handleClick() {
    if (!props.zipcode) return
    console.log("hello")
  }

  function handleEvent() {
    setCards([
      <SavedCard location={location} zipcode={zipcode} key={location} removeCard={removeCard} />,
    ])
  }

  // useEffect(() => {
  //   console.log(cards)
  // }, [cards])

  return (
    <>
      <div className="bg-slate-500 w-3/4 h-20 flex items-center justify-center border-4 border-slate-400 rounded shadow-sm shadow-black p-1 m-1">
        <button className="border-2 border-slate-700 rounded-xl shadow-md shadow-slate-700 grid place-items-center p-2 bg-slate-400">
          Add Current Location To Favorites
        </button>
        <div>
          {cards?.map((card) => {
            console.log(card)
            return card
          })}
        </div>
      </div>
      <button onClick={handleClick}>Create Card</button>
      <button onClick={handleEvent}>Handle Event</button>
    </>
  )
}

// Structure
// autogenerated cards
// displays name & zipcode
// Save to Favorites Button

// Functionality
// CRUD on user model - buttons to reflect this
// on click - sets SearchBar location call to saved zipcode

export default DashBoard
